[package]
name = "notes-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
serde = "1"
serde_json = "1"
config = "0"